In [1]:
from bs4 import BeautifulSoup
html='''<a id='a1' class="c1">V1</a>
<a id='a2' class="c1">V2</a>
<a id='a3' class="c3">V3</a>
'''
soup = BeautifulSoup(html,"html5lib")


In [7]:
import requests
from bs4 import BeautifulSoup
html='''<a id='a1' class="c1" href="https://google.com">Google</a>
<a id='a2' class="c1"  href="https://yahoo.com">Yahoo</a>
<a id='a3' class="c3" href="https://facebook.com">Facebook</a>
'''
soup = BeautifulSoup(html,"html5lib")
print(soup.find(id="a1").getText())
print(soup.find(id="a1").text)
print(soup.find(id="a1").get("href"))
tmpList = soup.find_all(class_ = "c1")
for tag in tmpList:
    print(tag.get("href"),tag.text)

Google
Google
https://google.com
https://google.com Google
https://yahoo.com Yahoo


# 使用html檔案練習

In [9]:
import bs4
htmlFile = open('web1.html',encoding="utf8",errors='ignore')
objSoup = bs4.BeautifulSoup(htmlFile, 'html5lib')
objTag = objSoup.find("h1")
print(objTag.text)

objTags = objSoup.find_all("h1")
for data in objTags:
    print(data.text)

class與id練習測試h1標籤
class與id練習測試h1標籤
國家首都資料表
h1標籤測試1
h1標籤測試2
h1標籤測試3
h1標籤測試4


In [10]:
import bs4
htmlFile = open('web1.html',encoding="utf8",errors='ignore')
objSoup = bs4.BeautifulSoup(htmlFile, 'html5lib')
objTag = objSoup.find_all("span",class_="class1")
for data in objTag:
    print(data)

<span class="class1">各種</span>


In [32]:
import requests
from bs4 import BeautifulSoup
url = "https://zh.wikipedia.org/zh-tw/2024年电影"
resp = requests.get(url)
resp.encoding = "utf-8"
soup = BeautifulSoup(resp.text,"html5lib")
movieTable = soup.find("table",class_="wikitable sortable")
tbodyObj = movieTable.find("tbody")
trList = tbodyObj.find_all("tr")
for inx in range(1,len(trList)):
    print("排名:",trList[inx].find("th").text,end="")
    print("片名:",trList[inx].find("a").text)
    print("全球票房:",trList[inx].find_all("td")[2].text)
    #print(trList[inx])
    

排名: 1
片名: 沙丘：第二部
全球票房: $711,844,358

排名: 2
片名: 哥吉拉與金剛：新帝國
全球票房: $566,982,315

排名: 3
片名: 功夫熊貓4
全球票房: $541,859,381

排名: 4
片名: 熱辣滾燙
全球票房: $479,597,304

排名: 5
片名: 飛馳人生2
全球票房: $468,849,262

排名: 6
片名: 第二十條
全球票房: $323,600,000

排名: 7
片名: 猩球崛起：王國誕生
全球票房: $302,312,115

排名: 8
片名: 熊出沒·逆轉時空
全球票房: $271,649,212

排名: 9
片名: 魔鬼剋星：冰天凍地
全球票房: $200,467,547

排名: 10
片名: 音樂傳奇卜馬利：人生愛與夢
全球票房: $179,393,170



## Numpy
+ 可做到的功能
  + 快速的多維陣列操作。
  + 可靠的科學功能函數庫。
  + 可協助繪圖工具進行繪圖。
+ NumPy 是幾乎每個科學 Python 應用程序或模組的核心，它提供了以向量化形式的快速 N-d 陣列類型可供操作。

In [36]:
import numpy as np
a= [1,2,3,4,7,9]
b= [3,5,3,6,7,9]
print(type(a))
print(a + b)
np1 = np.array(a)
np2 = np.array(b)
print(type(np1))
print(np1 + np2)

<class 'list'>
[1, 2, 3, 4, 7, 9, 3, 5, 3, 6, 7, 9]
<class 'numpy.ndarray'>
[ 4  7  6 10 14 18]


+ ndarray.ndim
   + 維度的數量。
+ ndarray.shape
   + 顯示出陣列在每個維度上的整數值。
+ ndarray.size
   + 陣列內元素的總數。
+ ndarray.dtype
   + 用來描述陣列中元素類型的對象。

In [42]:
import numpy as np
i = [[1,2,3],
     [4,5,6] ]
a = np.array(i)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

2
(2, 3)
6
int32


## 陣列初始化與重新規劃
+ 針對初始化這部分提供了多種方式：
+ 不做初始化
   + 例如：np.empty((2,4))
+ 全部規劃為 0
   + 例如：np.zeros((3,4))
+　全部規劃為 1
  + np.ones((5,2))
+ 全部規劃／填滿為某數，例如 6
   + 例如： np.full((3,3),6)
+ 建立對角矩陣，對角皆為 1，其他為 0
   + 例如： np.eye(3)
+ 建立對角矩陣，對角為 1,2,3,4，其他為 0
   + 例如： np.diag([1,2,3,4])
+ reshape((x,y)) 這個指令就可以將現有的陣列  重新規劃為 x 乘以 y 的陣列。 
+ np.arange(起始值, 結束值, 固定間隔)：也是產生一維陣列，和 np.array( ) 的差別在於 arange 擁有較大的彈性，而且元素數值是自動化產生。
+ np.linspace(起始值, 結束值, 起始與結束的區間內要產生幾個元素 )：只要給定陣列的區間(起始值、結束值)，就可以要求在這個區間內產生幾個元素。
+ arange(a,b,c)
   + 不包含 b 由 a 開始 以固定間隔 c 來取值
+ linspace(a,b,c,)
   + 包含 b 由 a 開始 切割成 c 個資料
+ linspace(a,b,c,endpoint=False)
   + 不包含 b 由 a 開始 切割成 c 個資料

In [49]:
import numpy as np
a = np.array([6,7,8,9])
b = np.arange(4)
print(a)
print(b)
c = a - b
print(c)
d = b**2
print(d)
f = np.array([5,-1,3,9,0])
print(f < 3)
f[f < 3] = 1
print(f)

[6 7 8 9]
[0 1 2 3]
[6 6 6 6]
[0 1 4 9]
[False  True False False  True]
[5 1 3 9 1]


In [66]:
import numpy as np
x = np.empty((2,4))
print(x)
z = np.zeros((2,4))
print(z)
one = np.ones((2,4))
print(one)
print(one*2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [68]:
import numpy as np
x = np.eye(3)
print(x)
y = np.diag([7,8,9,1,5])
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[7 0 0 0 0]
 [0 8 0 0 0]
 [0 0 9 0 0]
 [0 0 0 1 0]
 [0 0 0 0 5]]


In [81]:
import numpy as np
x = np.linspace(1,10,6)#(10-1)/(6-1)
print(x)
x = np.linspace(2,10,6)#(10-2)/(6-1)
print(x)
print((10-2)/(6-1))



[ 1.   2.8  4.6  6.4  8.2 10. ]
[ 2.   3.6  5.2  6.8  8.4 10. ]
1.6


In [85]:
import numpy as np
x = np.linspace(1,10,6)
a = x.reshape((2,3))
print(x.shape)
print(a.shape)
print(x)
print(a)

(6,)
(2, 3)
[ 1.   2.8  4.6  6.4  8.2 10. ]
[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]


## 陣列指定位置取值
+ 間隔選取 [::c]
  + 以 1 維陣列來說明 x[a:b:c]
  + a：選取資料的起始索引
  + b：選取資料的結束索引 +1
  + c：選取資料間隔，以索引值可以被此值整除的元素，不指定表示 1
+ 倒序 [::-1]
  + 只是單純的把順序反過來

## 陣列指定位置-給予一個整數
+ 關於指定位置  [row,column]
+ 假設給予一個整數為 N
 + 如果是給固定的 N，那就代表 row 或 column 等於 N。
 + 如果是 N：，那就代表 row 或 column 大於等於 N 的區域。
 + 如果是：N，那就代表 row 或 column 小於 N 的區域。 
 + 如果是：，那就代表 row 或 column 是任意欄位。

In [97]:
import numpy as np
a = np.arange(1,10).reshape((3,3))
print(a)
print(a[0])
print(a[0][1])
print(a[0,1])
print(a[2,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
2
2
8


In [105]:
import numpy as np
a = np.arange(1,10).reshape((3,3))
print(a)
a2 = a[:,1]
print(a2)
a3 = a[2,:]
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5 8]
[7 8 9]


In [110]:
import numpy as np
a = np.arange(1,10).reshape((3,3))
print(a)
print("="*70)
print(a[:2,1:])
print("="*70)
print(a[1:,:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[[4 5]
 [7 8]]


In [121]:
import numpy as np
a=np.arange(0,36).reshape((6,6))
print(a)

"""----1
[3,4]
"""
print("-----1")
print(a[0,3:5])
""" ---2
[[28 29]
 [34 35]]
"""
print("-----2")
print(a[4:,4:])
print("-----2-2")
print(a[-2:,-2:])
"""
---3--
[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]]
 """
print("---3--")
print(a[:3,:3])
"""
---4--
[ 2  8 14 20 26 32]
"""
print("---4--")
print(a[:,2])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-----1
[3 4]
-----2
[[28 29]
 [34 35]]
-----2-2
[[28 29]
 [34 35]]
---3--
[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]]
---4--
[ 2  8 14 20 26 32]


## 重設新陣列
+ resize 這個動作會依據原本的陣列再設定指定大小的新陣列。 
+ resize 動作的參數如下：
+ numpy.resize(arr1，shape1)
  + arr1：原本的陣列
  + shape1：新規劃的大小
+ 如果規劃的新陣列比較大，將會重新複製原有陣列的資料，填滿新的儲存格。
+ resize 這個動作***建立新的陣列***，而 reshape 則是依據原有的重新規劃，仍會受到原有陣列影響。
+ transpose()轉置

In [130]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])
print(a.shape)
print()
b = a.reshape(3,2)
print(b)
print(b.shape)

print("=======a==========")
a[0,1] = 100
print(a)
print("=======b==========")
print(b)

(2, 3)



ValueError: cannot reshape array of size 6 into shape (10,10)

### resize

In [131]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])
print(a.shape)
print()
b = np.resize(a,(3,2))
print(b)
a[0,1] = 100
print(b)
c= np.resize(a,(10,10))
print(c)

(2, 3)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[  1 100   3   4   5   6   1 100   3   4]
 [  5   6   1 100   3   4   5   6   1 100]
 [  3   4   5   6   1 100   3   4   5   6]
 [  1 100   3   4   5   6   1 100   3   4]
 [  5   6   1 100   3   4   5   6   1 100]
 [  3   4   5   6   1 100   3   4   5   6]
 [  1 100   3   4   5   6   1 100   3   4]
 [  5   6   1 100   3   4   5   6   1 100]
 [  3   4   5   6   1 100   3   4   5   6]
 [  1 100   3   4   5   6   1 100   3   4]]


### transpose

In [138]:
import numpy as np
newArray = np.arange(10).reshape(2,5)
print(newArray)
print(newArray.transpose())
print(newArray.T)
tArray = newArray.T
print(tArray)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


## 讀存檔案
+ 可使用 np.loadtxt( ) 方法進行檔案的讀取。
+ 若不需要讀入第一列，可使用 skiprows=1 來忽略第一列。
+ 若我們的資料是利用 ‘,’ 當作資料與資料之間的分格符號，可使用 delimiter=‘ , ’ 設定，預設為空白。
+ 若設定 unpack=True 代表可以將 Column 分別切出來 (預設為False)。
+ 但是，當我們欲要讀的檔案，裡面有遺失值的時候，loadtxt 這個動作將會產生錯誤。
loadtxt( ) 必須是在每一 row 都有相同數量的 value 下，才可以使用。
  + 建議改用 genfromtxt( ) 方法 ，它可以針對遺失值進行處理。
  + 參數加上 filling_values 可以把原本缺失的資料補上指定的資料。
+ 可利用 savetxt( ) 將資料存進檔案裡面保存。
+ genfromtxt 可透過 skip_header=1  參數忽略第一列。
+ 碰到遺失值的處理：
  + loadtxt 碰到遺失值會產生錯誤。
  + genfromtxt 碰到遺失值會以 nan 來表示。
+ genfromtxt 進行存取時：
  + 資料預設為浮點數(科學記數法)，所以建議儲存的時候以 fmt 進行格式設定。
  + 開啟時若資料為整數，請加入 dtype 設定為 int。

In [144]:
import numpy as np
x = np.loadtxt("data1.csv",delimiter=",")
print(x)
print(type(x))
y,z = np.loadtxt("data1.csv",delimiter=",",unpack=True)
print("y:",y)
print("z:",z)
print("y > z:",y > z)
n = y[y > z]
print(n)

[[0.2 0.1]
 [0.4 0.3]
 [0.1 0.6]
 [0.1 0.3]
 [0.5 0.3]]
<class 'numpy.ndarray'>
value1: [0.2 0.4 0.1 0.1 0.5]
value2: [0.1 0.3 0.6 0.3 0.3]
y > z: [ True  True False False  True]
[0.2 0.4 0.5]


## 總和最大與最小
+ np.sum( ) 代表某一個陣列內容的總和，也可以指定這個陣列的哪一軸 (axis) 內容總和。
+ np.min( ) 代表某一個陣列內容的最小值，也可以指定這個陣列的哪一軸 (axis) 內容的最小值。
+ np.max( ) 代表某一個陣列內容的最大值，也可以指定這個陣列的哪一軸 (axis) 內容的最大值。
+ amin 與 min 是相同功能的方法。
+ amax 與 max 是相同功能的方法。

### 總和sum()

In [149]:
import numpy as np
a = np.array([[0, 30,45],
              [60,75,90]])
print(a)
b = np.sum(a)
print(b)
b = np.sum(a,axis=0)
print(b)
b = np.sum(a,axis=1)
print(b)

[[ 0 30 45]
 [60 75 90]]
300
[ 60 105 135]
[ 75 225]


In [ ]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])
print(a.shape)
print()
b = a.reshape(3,2)
print(b)
print(b.shape)

print("=======a==========")
print(a)
a[0,1] = 100
print("=======b==========")
print(b)

(2, 3)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
=======a==========
[[1 2 3]
 [4 5 6]]
=======b==========
[[1 2]
 [3 4]
 [5 6]]


### max() min()

In [154]:
import numpy as np
a = np.array([[0, 30,45],
              [60,75,90]])
print(a)
b = np.max(a)
print(b)
bi = np.max(a,axis=0)
print(bi)
bi = np.max(a,axis=1)
print(bi)

[[ 0 30 45]
 [60 75 90]]
90
[60 75 90]
[45 90]


## 中位數與平均
+ median( ) 方法可取出陣列或陣列中指定的軸之中位數。
+ 把所有值高低排序後找出正中間的一個作爲中位數。如果資料數量為偶數，則中位數取最中間的兩個數值的平均數。
+ 參數：
  + array：陣列
  + axis：軸
+ mean( ) 方法可取出陣列或陣列中指定的軸之平均數。
+ 平均值就是把陣列或指定軸的所有資料除以數量後的數值。
+ 參數：
    + array：陣列 
    + axis：軸
+ average( ) 方法與 mean( ) 方法相似，但可以加入權重進行計算。
+ 計算公式為 ((資料*權重)相加)/(權重相加)
+ 參數：
  + array：陣列
  + axis：軸
  + weights：權重，若沒有則設定為 1
  + returned：若設定為 true，代表返回計算結果跟權重相加總合兩筆資料，若沒有設定或設定  false 則只有計算結果 
+ 沒有指定權重時與一般平均值相同。
+ 加權平均值是由每個資料乘以權重以反映加上重要性因素後產生的平均值。
+ average( ) 使用時若沒有指定軸，則陣列將被平坦化。
+ 假設有個陣列資料為 [1,2,3,4]，相應的權重 [40,30,20,10]，加權平均數是這樣：
    (1x40+2x30+3x20+4x10)/(40+30+20+10)

In [157]:
import numpy as np
a = np.array([[0, 30,45],
              [60,75,90]])
b = np.mean(a)
print(b)
b = np.mean(a,axis=0)
print(b)
b = np.mean(a,axis=1)
print(b)

50.0
[30.  52.5 67.5]
[25. 75.]


In [158]:
import numpy as np
a = np.array([1,2,3,4])
b=np.average(a)
print(b)
print( )
wts = np.array([4,3,2,1])
b=np.average(a,weights = wts)
print(b)
print( )
b=np.average([1,2,3,4],weights = [4,3,2,1], returned = True)
#(1*4+2*3+3*2+4*1)/(4+3+2+1)  
# 20/10  = 2
#4+3+2+1 = 10
#
print(b)
print()

2.5

2.0

(2.0, 10.0)



## 中位數

In [162]:
import numpy as np
a = np.array([[0, 30,45],[60,75,90]])
print(a)
b = np.median(a)
print(b)
b = np.median(a,axis=0)
print(b)
b = np.median(a,axis=1)
print(b)

[[ 0 30 45]
 [60 75 90]]
52.5
[30.  52.5 67.5]
[30. 75.]


## 變異數與標準差
+ 變異數代表所有資料到平均數的距離之平方。
+ 標準差代表變異數開平方根，也就是可依此表示資料的分散程度。
+ var( ) 代表由陣列取得變異數的方法。
+ std( ) 代表由陣列取得標準差的方法。

+ 定義：

+ 變異數代表((每一個資料-平均值)平方後的加總結果)/總個數。

+ 標準差是變異數的開根號結果。

In [167]:
import numpy as np
a = np.array([1,2,3,4])
b = np.var(a)#變異數
print(b)
b = np.std(a)#標準差
print(b)

1.25
1.118033988749895
